import React, { createContext, useContext, useEffect, useState } from "react";

export const languages = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "ru", name: "Russian", nativeName: "Русский" },
  { code: "zh", name: "Chinese", nativeName: "中文" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
  { code: "ko", name: "Korean", nativeName: "한국어" },
  { code: "ar", name: "Arabic", nativeName: "العربية" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "pl", name: "Polish", nativeName: "Polski" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "th", name: "Thai", nativeName: "ไทย" },
];

interface LanguageContextType {
  language: string;
  setLanguage: (code: string) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<string, string>> = {
  en: {
    "welcome.greeting": "Hello, I'm AquaLibriaAI",
    "welcome.subtitle": "Your calm, intelligent companion for thinking, coding, learning, and creating.",
    "welcome.continue": "Continue",
    "intent.question": "What would you like to use me for today?",
    "intent.coding": "Coding",
    "intent.learning": "Learning",
    "intent.images": "Image Generation",
    "intent.quotes": "Quote Creation",
    "chat.placeholder": "Message AquaLibriaAI...",
    "chat.send": "Send",
    "chat.empty.title": "How can I help you today?",
    "chat.empty.subtitle": "Start a conversation or use the + menu for more options",
    "menu.history": "Chat History",
    "menu.search": "Search Chats",
    "menu.coding": "Coding Partner",
    "menu.language": "Language",
    "menu.theme": "Theme",
    "menu.settings": "Settings",
    "menu.newChat": "New Chat",
    "menu.logout": "Sign Out",
    "login.title": "Welcome back",
    "login.subtitle": "Sign in to continue your journey",
    "login.email": "Email",
    "login.password": "Password",
    "login.signin": "Sign In",
    "login.google": "Continue with Google",
    "login.noAccount": "Don't have an account?",
    "login.register": "Create one",
    "register.title": "Create your account",
    "register.subtitle": "Begin your journey with AquaLibriaAI",
    "register.email": "Email",
    "register.password": "Password",
    "register.confirm": "Confirm Password",
    "register.create": "Create Account",
    "register.google": "Continue with Google",
    "register.hasAccount": "Already have an account?",
    "register.login": "Sign in",
    "register.verify": "Check your email",
    "register.verifyMessage": "We've sent a verification link to your email. Please check your inbox (and spam folder) to verify your account.",
    "settings.title": "Settings",
    "settings.ai": "AI Settings",
    "settings.aiName": "AI Name",
    "settings.personality": "Personality",
    "settings.customPersonality": "Custom Instructions",
    "settings.customPersonalityPlaceholder": "Add custom instructions for the AI...",
    "settings.chat": "Chat Management",
    "settings.export": "Export Chat History",
    "settings.import": "Import Chat History",
    "settings.appearance": "Appearance",
    "settings.memory": "AI Memory",
    "settings.memoryDesc": "AquaLibriaAI can remember your name, preferences, and habits to provide a more personalized experience.",
    "settings.rememberName": "Remember my name",
    "settings.rememberPrefs": "Remember preferences",
    "settings.rememberStyle": "Remember writing style",
    "settings.privacy": "Privacy",
    "settings.privacyPolicy": "Privacy Policy",
    "settings.profile": "Profile",
    "plus.uploadImage": "Upload Image",
    "plus.chooseModel": "Choose Model",
    "plus.generateImage": "Generate Image",
    "plus.deepResearch": "Deep Research",
    "plus.spotifySearch": "Spotify Search",
    "plus.quoteMaker": "Quote Maker",
    "mode.research": "Deep Research Mode",
    "mode.image": "Image Generation Mode",
    "mode.spotify": "Spotify Search Mode",
    "mode.quote": "Quote Maker Mode",
    "mode.cancel": "Cancel",
    "loading.thinking": "Thinking...",
    "loading.research": "Researching...",
    "loading.image": "Generating image...",
    "loading.quote": "Creating quote...",
    "loading.uploading": "Uploading image...",
    "loading.analyzing": "Analyzing image...",
    "error.api": "Failed to get response",
    "error.generic": "Something went wrong. Please try again.",
    "error.upload": "Failed to upload image",
    "quote.prompt": "Enter your quote text",
    "quote.author": "Author (optional)",
    "quote.style": "Style",
    "quote.create": "Create Quote",
    "history.empty": "No chat history yet",
    "history.delete": "Delete",
    "history.deleteAll": "Delete All",
    "history.title": "Chat History",
    "search.placeholder": "Search chats...",
    "search.noResults": "No results found",
    "coding.title": "Coding Partner",
    "coding.placeholder": "Describe what you want to code...",
    "coding.empty.title": "Ready to code",
    "coding.empty.subtitle": "Describe your coding task and I'll help you build it",
  },
  es: {
    "welcome.greeting": "Hola, soy AquaLibriaAI",
    "welcome.subtitle": "Tu compañero tranquilo e inteligente para pensar, programar, aprender y crear.",
    "welcome.continue": "Continuar",
    "intent.question": "¿Para qué te gustaría usarme hoy?",
    "intent.coding": "Programación",
    "intent.learning": "Aprendizaje",
    "intent.images": "Generación de Imágenes",
    "intent.quotes": "Creación de Citas",
    "chat.placeholder": "Mensaje a AquaLibriaAI...",
    "chat.send": "Enviar",
    "chat.empty.title": "¿Cómo puedo ayudarte hoy?",
    "chat.empty.subtitle": "Inicia una conversación o usa el menú + para más opciones",
    "menu.history": "Historial de Chat",
    "menu.search": "Buscar Chats",
    "menu.coding": "Compañero de Código",
    "menu.language": "Idioma",
    "menu.theme": "Tema",
    "menu.settings": "Configuración",
    "menu.newChat": "Nuevo Chat",
    "menu.logout": "Cerrar Sesión",
    "login.title": "Bienvenido de nuevo",
    "login.subtitle": "Inicia sesión para continuar",
    "login.email": "Correo electrónico",
    "login.password": "Contraseña",
    "login.signin": "Iniciar Sesión",
    "login.google": "Continuar con Google",
    "login.noAccount": "¿No tienes cuenta?",
    "login.register": "Crear una",
    "register.title": "Crea tu cuenta",
    "register.subtitle": "Comienza tu viaje con AquaLibriaAI",
    "settings.title": "Configuración",
    "settings.profile": "Perfil",
    "plus.uploadImage": "Subir Imagen",
    "plus.generateImage": "Generar Imagen",
    "plus.deepResearch": "Investigación Profunda",
    "plus.spotifySearch": "Buscar en Spotify",
    "plus.quoteMaker": "Creador de Citas",
    "loading.thinking": "Pensando...",
    "loading.research": "Investigando...",
    "loading.image": "Generando imagen...",
    "coding.title": "Compañero de Código",
    "coding.placeholder": "Describe lo que quieres programar...",
    "history.title": "Historial de Chat",
    "search.placeholder": "Buscar chats...",
  },
  fr: {
    "welcome.greeting": "Bonjour, je suis AquaLibriaAI",
    "welcome.subtitle": "Votre compagnon calme et intelligent pour réfléchir, coder, apprendre et créer.",
    "welcome.continue": "Continuer",
    "intent.question": "Pour quoi aimeriez-vous m'utiliser aujourd'hui?",
    "intent.coding": "Programmation",
    "intent.learning": "Apprentissage",
    "intent.images": "Génération d'Images",
    "intent.quotes": "Création de Citations",
    "chat.placeholder": "Message à AquaLibriaAI...",
    "chat.empty.title": "Comment puis-je vous aider?",
    "chat.empty.subtitle": "Commencez une conversation ou utilisez le menu +",
    "menu.history": "Historique des Chats",
    "menu.coding": "Partenaire de Code",
    "menu.language": "Langue",
    "menu.theme": "Thème",
    "menu.settings": "Paramètres",
    "menu.logout": "Déconnexion",
    "login.title": "Bienvenue",
    "login.subtitle": "Connectez-vous pour continuer",
    "settings.title": "Paramètres",
    "settings.profile": "Profil",
    "loading.thinking": "Réflexion...",
    "coding.title": "Partenaire de Code",
    "history.title": "Historique des Chats",
  },
  de: {
    "welcome.greeting": "Hallo, ich bin AquaLibriaAI",
    "welcome.subtitle": "Ihr ruhiger, intelligenter Begleiter zum Denken, Programmieren, Lernen und Erstellen.",
    "welcome.continue": "Fortfahren",
    "chat.placeholder": "Nachricht an AquaLibriaAI...",
    "chat.empty.title": "Wie kann ich Ihnen helfen?",
    "menu.history": "Chat-Verlauf",
    "menu.coding": "Coding-Partner",
    "menu.language": "Sprache",
    "menu.theme": "Thema",
    "menu.settings": "Einstellungen",
    "menu.logout": "Abmelden",
    "settings.title": "Einstellungen",
    "settings.profile": "Profil",
    "loading.thinking": "Denke nach...",
    "coding.title": "Coding-Partner",
    "history.title": "Chat-Verlauf",
  },
  it: {
    "welcome.greeting": "Ciao, sono AquaLibriaAI",
    "welcome.subtitle": "Il tuo compagno calmo e intelligente per pensare, programmare, imparare e creare.",
    "welcome.continue": "Continua",
    "chat.placeholder": "Messaggio a AquaLibriaAI...",
    "menu.history": "Cronologia Chat",
    "menu.coding": "Partner di Coding",
    "menu.settings": "Impostazioni",
    "settings.title": "Impostazioni",
    "loading.thinking": "Pensando...",
    "coding.title": "Partner di Coding",
  },
  pt: {
    "welcome.greeting": "Olá, sou AquaLibriaAI",
    "welcome.subtitle": "Seu companheiro calmo e inteligente para pensar, programar, aprender e criar.",
    "welcome.continue": "Continuar",
    "chat.placeholder": "Mensagem para AquaLibriaAI...",
    "menu.history": "Histórico de Chat",
    "menu.coding": "Parceiro de Código",
    "menu.settings": "Configurações",
    "settings.title": "Configurações",
    "loading.thinking": "Pensando...",
    "coding.title": "Parceiro de Código",
  },
  ru: {
    "welcome.greeting": "Привет, я AquaLibriaAI",
    "welcome.subtitle": "Ваш спокойный и умный компаньон для размышлений, программирования, обучения и творчества.",
    "welcome.continue": "Продолжить",
    "chat.placeholder": "Сообщение для AquaLibriaAI...",
    "menu.history": "История чата",
    "menu.coding": "Партнёр по коду",
    "menu.settings": "Настройки",
    "settings.title": "Настройки",
    "loading.thinking": "Думаю...",
    "coding.title": "Партнёр по коду",
  },
  zh: {
    "welcome.greeting": "你好，我是AquaLibriaAI",
    "welcome.subtitle": "您平静而智能的思考、编程、学习和创作伙伴。",
    "welcome.continue": "继续",
    "chat.placeholder": "给AquaLibriaAI发消息...",
    "chat.empty.title": "今天我能帮你什么？",
    "menu.history": "聊天记录",
    "menu.coding": "编程伙伴",
    "menu.settings": "设置",
    "settings.title": "设置",
    "loading.thinking": "思考中...",
    "coding.title": "编程伙伴",
  },
  ja: {
    "welcome.greeting": "こんにちは、AquaLibriaAIです",
    "welcome.subtitle": "思考、コーディング、学習、創造のための穏やかで知的なコンパニオン。",
    "welcome.continue": "続ける",
    "chat.placeholder": "AquaLibriaAIにメッセージ...",
    "menu.history": "チャット履歴",
    "menu.coding": "コーディングパートナー",
    "menu.settings": "設定",
    "settings.title": "設定",
    "loading.thinking": "考え中...",
    "coding.title": "コーディングパートナー",
  },
  ko: {
    "welcome.greeting": "안녕하세요, AquaLibriaAI입니다",
    "welcome.subtitle": "생각, 코딩, 학습, 창작을 위한 차분하고 지능적인 동반자입니다.",
    "welcome.continue": "계속",
    "chat.placeholder": "AquaLibriaAI에게 메시지...",
    "menu.history": "채팅 기록",
    "menu.coding": "코딩 파트너",
    "menu.settings": "설정",
    "settings.title": "설정",
    "loading.thinking": "생각 중...",
    "coding.title": "코딩 파트너",
  },
  ar: {
    "welcome.greeting": "مرحباً، أنا AquaLibriaAI",
    "welcome.subtitle": "رفيقك الهادئ والذكي للتفكير والبرمجة والتعلم والإبداع.",
    "welcome.continue": "متابعة",
    "chat.placeholder": "رسالة إلى AquaLibriaAI...",
    "menu.history": "سجل المحادثات",
    "menu.coding": "شريك البرمجة",
    "menu.settings": "الإعدادات",
    "settings.title": "الإعدادات",
    "loading.thinking": "جارٍ التفكير...",
    "coding.title": "شريك البرمجة",
  },
  hi: {
    "welcome.greeting": "नमस्ते, मैं AquaLibriaAI हूं",
    "welcome.subtitle": "सोचने, कोडिंग, सीखने और बनाने के लिए आपका शांत, बुद्धिमान साथी।",
    "welcome.continue": "जारी रखें",
    "chat.placeholder": "AquaLibriaAI को संदेश...",
    "menu.history": "चैट इतिहास",
    "menu.coding": "कोडिंग पार्टनर",
    "menu.settings": "सेटिंग्स",
    "settings.title": "सेटिंग्स",
    "loading.thinking": "सोच रहा हूं...",
    "coding.title": "कोडिंग पार्टनर",
  },
  nl: {
    "welcome.greeting": "Hallo, ik ben AquaLibriaAI",
    "welcome.subtitle": "Je rustige, intelligente metgezel voor denken, coderen, leren en creëren.",
    "welcome.continue": "Doorgaan",
    "chat.placeholder": "Bericht aan AquaLibriaAI...",
    "menu.history": "Chatgeschiedenis",
    "menu.coding": "Codeerpartner",
    "menu.settings": "Instellingen",
    "settings.title": "Instellingen",
    "loading.thinking": "Aan het denken...",
    "coding.title": "Codeerpartner",
  },
  pl: {
    "welcome.greeting": "Cześć, jestem AquaLibriaAI",
    "welcome.subtitle": "Twój spokojny, inteligentny towarzysz do myślenia, kodowania, nauki i tworzenia.",
    "welcome.continue": "Kontynuuj",
    "chat.placeholder": "Wiadomość do AquaLibriaAI...",
    "menu.history": "Historia czatu",
    "menu.coding": "Partner kodowania",
    "menu.settings": "Ustawienia",
    "settings.title": "Ustawienia",
    "loading.thinking": "Myślę...",
    "coding.title": "Partner kodowania",
  },
  tr: {
    "welcome.greeting": "Merhaba, ben AquaLibriaAI",
    "welcome.subtitle": "Düşünme, kodlama, öğrenme ve yaratma için sakin, zeki yoldaşınız.",
    "welcome.continue": "Devam",
    "chat.placeholder": "AquaLibriaAI'ye mesaj...",
    "menu.history": "Sohbet Geçmişi",
    "menu.coding": "Kodlama Ortağı",
    "menu.settings": "Ayarlar",
    "settings.title": "Ayarlar",
    "loading.thinking": "Düşünüyorum...",
    "coding.title": "Kodlama Ortağı",
  },
  id: {
    "welcome.greeting": "Halo, saya AquaLibriaAI",
    "welcome.subtitle": "Teman tenang dan cerdas Anda untuk berpikir, coding, belajar, dan berkreasi.",
    "welcome.continue": "Lanjutkan",
    "chat.placeholder": "Pesan ke AquaLibriaAI...",
    "menu.history": "Riwayat Chat",
    "menu.coding": "Partner Coding",
    "menu.settings": "Pengaturan",
    "settings.title": "Pengaturan",
    "loading.thinking": "Berpikir...",
    "coding.title": "Partner Coding",
  },
  vi: {
    "welcome.greeting": "Xin chào, tôi là AquaLibriaAI",
    "welcome.subtitle": "Người bạn đồng hành bình tĩnh và thông minh cho suy nghĩ, lập trình, học tập và sáng tạo.",
    "welcome.continue": "Tiếp tục",
    "chat.placeholder": "Nhắn tin cho AquaLibriaAI...",
    "menu.history": "Lịch sử trò chuyện",
    "menu.coding": "Đối tác lập trình",
    "menu.settings": "Cài đặt",
    "settings.title": "Cài đặt",
    "loading.thinking": "Đang suy nghĩ...",
    "coding.title": "Đối tác lập trình",
  },
  th: {
    "welcome.greeting": "สวัสดี ฉันคือ AquaLibriaAI",
    "welcome.subtitle": "เพื่อนคู่คิดที่สงบและชาญฉลาดของคุณสำหรับการคิด เขียนโค้ด เรียนรู้ และสร้างสรรค์",
    "welcome.continue": "ดำเนินการต่อ",
    "chat.placeholder": "ส่งข้อความถึง AquaLibriaAI...",
    "menu.history": "ประวัติแชท",
    "menu.coding": "พาร์ทเนอร์โค้ด",
    "menu.settings": "การตั้งค่า",
    "settings.title": "การตั้งค่า",
    "loading.thinking": "กำลังคิด...",
    "coding.title": "พาร์ทเนอร์โค้ด",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<string>(() => {
    const stored = localStorage.getItem("aqua-language");
    if (stored) return stored;
    
    const browserLang = navigator.language.split("-")[0];
    const supported = languages.find((l) => l.code === browserLang);
    return supported ? browserLang : "en";
  });

  useEffect(() => {
    localStorage.setItem("aqua-language", language);
  }, [language]);

  const setLanguage = (code: string) => {
    setLanguageState(code);
  };

  const t = (key: string): string => {
    const langTranslations = translations[language] || translations.en;
    return langTranslations[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};