import React, { createContext, useContext, useEffect, useState } from "react";

// Complete list of all languages A-Z
export const languages = [
  { code: "af", name: "Afrikaans", nativeName: "Afrikaans" },
  { code: "sq", name: "Albanian", nativeName: "Shqip" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "ar", name: "Arabic", nativeName: "العربية" },
  { code: "hy", name: "Armenian", nativeName: "Հայերdelays" },
  { code: "az", name: "Azerbaijani", nativeName: "Azərbaycan" },
  { code: "eu", name: "Basque", nativeName: "Euskara" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "bg", name: "Bulgarian", nativeName: "Български" },
  { code: "my", name: "Burmese", nativeName: "မြန်မာ" },
  { code: "ca", name: "Catalan", nativeName: "Català" },
  { code: "zh", name: "Chinese", nativeName: "中文" },
  { code: "hr", name: "Croatian", nativeName: "Hrvatski" },
  { code: "cs", name: "Czech", nativeName: "Čeština" },
  { code: "da", name: "Danish", nativeName: "Dansk" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "en", name: "English", nativeName: "English" },
  { code: "et", name: "Estonian", nativeName: "Eesti" },
  { code: "fi", name: "Finnish", nativeName: "Suomi" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "gl", name: "Galician", nativeName: "Galego" },
  { code: "ka", name: "Georgian", nativeName: "ქართული" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "ht", name: "Haitian Creole", nativeName: "Kreyòl Ayisyen" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "he", name: "Hebrew", nativeName: "עברית" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar" },
  { code: "is", name: "Icelandic", nativeName: "Íslenska" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
  { code: "jv", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "kk", name: "Kazakh", nativeName: "Қазақша" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "ko", name: "Korean", nativeName: "한국어" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "lv", name: "Latvian", nativeName: "Latviešu" },
  { code: "lt", name: "Lithuanian", nativeName: "Lietuvių" },
  { code: "lb", name: "Luxembourgish", nativeName: "Lëtzebuergesch" },
  { code: "mk", name: "Macedonian", nativeName: "Македонски" },
  { code: "mg", name: "Malagasy", nativeName: "Malagasy" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "mt", name: "Maltese", nativeName: "Malti" },
  { code: "mi", name: "Maori", nativeName: "Māori" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "no", name: "Norwegian", nativeName: "Norsk" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "fa", name: "Persian", nativeName: "فارسی" },
  { code: "pl", name: "Polish", nativeName: "Polski" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "ro", name: "Romanian", nativeName: "Română" },
  { code: "ru", name: "Russian", nativeName: "Русский" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Samoa" },
  { code: "gd", name: "Scottish Gaelic", nativeName: "Gàidhlig" },
  { code: "sr", name: "Serbian", nativeName: "Српски" },
  { code: "st", name: "Sesotho", nativeName: "Sesotho" },
  { code: "sn", name: "Shona", nativeName: "Shona" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "si", name: "Sinhala", nativeName: "සිංහල" },
  { code: "sk", name: "Slovak", nativeName: "Slovenčina" },
  { code: "sl", name: "Slovenian", nativeName: "Slovenščina" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "su", name: "Sundanese", nativeName: "Basa Sunda" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili" },
  { code: "sv", name: "Swedish", nativeName: "Svenska" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "tg", name: "Tajik", nativeName: "Тоҷикӣ" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "th", name: "Thai", nativeName: "ไทย" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "yi", name: "Yiddish", nativeName: "ייִדיש" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
];

interface LanguageContextType {
  language: string;
  setLanguage: (code: string) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<string, string>> = {
  en: {
    "welcome.greeting": "Hello, I'm AquaLibriaAI",
    "welcome.subtitle": "Your calm, intelligent companion for thinking, coding, learning, and creating.",
    "welcome.continue": "Continue",
    "intent.question": "What would you like to use me for today?",
    "intent.coding": "Coding",
    "intent.learning": "Learning",
    "intent.images": "Image Generation",
    "intent.quotes": "Quote Creation",
    "chat.placeholder": "Message AquaLibriaAI...",
    "chat.send": "Send",
    "chat.empty.title": "How can I help you today?",
    "chat.empty.subtitle": "Start a conversation or use the + menu for more options",
    "menu.history": "Chat History",
    "menu.search": "Search Chats",
    "menu.coding": "Coding Partner",
    "menu.language": "Language",
    "menu.theme": "Theme",
    "menu.settings": "Settings",
    "menu.newChat": "New Chat",
    "menu.logout": "Sign Out",
    "login.title": "Welcome back",
    "login.subtitle": "Sign in to continue your journey",
    "login.email": "Email",
    "login.password": "Password",
    "login.signin": "Sign In",
    "login.google": "Continue with Google",
    "login.noAccount": "Don't have an account?",
    "login.register": "Create one",
    "register.title": "Create your account",
    "register.subtitle": "Begin your journey with AquaLibriaAI",
    "settings.title": "Settings",
    "settings.ai": "AI Settings",
    "settings.aiName": "AI Name",
    "settings.personality": "Personality",
    "settings.customPersonality": "Custom Instructions",
    "settings.customPersonalityPlaceholder": "Add custom instructions for the AI...",
    "settings.chat": "Chat Management",
    "settings.export": "Export Chat History",
    "settings.import": "Import Chat History",
    "settings.memory": "AI Memory",
    "settings.rememberName": "Remember my name",
    "settings.rememberPrefs": "Remember preferences",
    "settings.rememberStyle": "Remember writing style",
    "settings.privacy": "Privacy",
    "settings.privacyPolicy": "Privacy Policy",
    "settings.profile": "Profile",
    "plus.uploadImage": "Upload Image",
    "plus.chooseModel": "Choose Model",
    "plus.generateImage": "Generate Image",
    "plus.deepResearch": "Deep Research",
    "plus.spotifySearch": "Spotify Search",
    "plus.quoteMaker": "Quote Maker",
    "loading.thinking": "Thinking...",
    "coding.title": "Coding Partner",
    "history.title": "Chat History",
  },
  id: {
    "welcome.greeting": "Halo, saya AquaLibriaAI",
    "welcome.subtitle": "Teman tenang dan cerdas Anda untuk berpikir, coding, belajar, dan berkreasi.",
    "welcome.continue": "Lanjutkan",
    "intent.question": "Apa yang ingin Anda lakukan hari ini?",
    "intent.coding": "Coding",
    "intent.learning": "Belajar",
    "intent.images": "Buat Gambar",
    "intent.quotes": "Buat Quote",
    "chat.placeholder": "Pesan ke AquaLibriaAI...",
    "chat.send": "Kirim",
    "chat.empty.title": "Ada yang bisa saya bantu?",
    "chat.empty.subtitle": "Mulai percakapan atau gunakan menu + untuk opsi lainnya",
    "menu.history": "Riwayat Chat",
    "menu.search": "Cari Chat",
    "menu.coding": "Partner Coding",
    "menu.language": "Bahasa",
    "menu.theme": "Tema",
    "menu.settings": "Pengaturan",
    "menu.newChat": "Chat Baru",
    "menu.logout": "Keluar",
    "settings.title": "Pengaturan",
    "settings.aiName": "Nama AI",
    "settings.personality": "Kepribadian",
    "settings.customPersonality": "Instruksi Kustom",
    "settings.customPersonalityPlaceholder": "Tambahkan instruksi kustom untuk AI...",
    "settings.chat": "Manajemen Chat",
    "settings.export": "Ekspor Riwayat",
    "settings.import": "Impor Riwayat",
    "settings.memory": "Memori AI",
    "settings.rememberName": "Ingat nama saya",
    "settings.rememberPrefs": "Ingat preferensi",
    "settings.rememberStyle": "Ingat gaya penulisan",
    "settings.privacyPolicy": "Kebijakan Privasi",
    "loading.thinking": "Berpikir...",
    "coding.title": "Partner Coding",
    "history.title": "Riwayat Chat",
  },
  es: {
    "welcome.greeting": "Hola, soy AquaLibriaAI",
    "welcome.subtitle": "Tu compañero tranquilo e inteligente para pensar, programar, aprender y crear.",
    "welcome.continue": "Continuar",
    "chat.placeholder": "Mensaje a AquaLibriaAI...",
    "chat.empty.title": "¿Cómo puedo ayudarte hoy?",
    "menu.history": "Historial de Chat",
    "menu.coding": "Compañero de Código",
    "menu.language": "Idioma",
    "menu.theme": "Tema",
    "menu.settings": "Configuración",
    "menu.logout": "Cerrar Sesión",
    "settings.title": "Configuración",
    "loading.thinking": "Pensando...",
  },
  fr: {
    "welcome.greeting": "Bonjour, je suis AquaLibriaAI",
    "welcome.subtitle": "Votre compagnon calme et intelligent pour réfléchir, coder, apprendre et créer.",
    "welcome.continue": "Continuer",
    "chat.placeholder": "Message à AquaLibriaAI...",
    "chat.empty.title": "Comment puis-je vous aider?",
    "menu.history": "Historique des Chats",
    "menu.coding": "Partenaire de Code",
    "menu.language": "Langue",
    "menu.theme": "Thème",
    "menu.settings": "Paramètres",
    "menu.logout": "Déconnexion",
    "settings.title": "Paramètres",
    "loading.thinking": "Réflexion...",
  },
  de: {
    "welcome.greeting": "Hallo, ich bin AquaLibriaAI",
    "welcome.subtitle": "Ihr ruhiger, intelligenter Begleiter zum Denken, Programmieren, Lernen und Erstellen.",
    "welcome.continue": "Fortfahren",
    "chat.placeholder": "Nachricht an AquaLibriaAI...",
    "chat.empty.title": "Wie kann ich Ihnen helfen?",
    "menu.history": "Chat-Verlauf",
    "menu.coding": "Coding-Partner",
    "menu.language": "Sprache",
    "menu.theme": "Thema",
    "menu.settings": "Einstellungen",
    "menu.logout": "Abmelden",
    "settings.title": "Einstellungen",
    "loading.thinking": "Denke nach...",
  },
  zh: {
    "welcome.greeting": "你好，我是AquaLibriaAI",
    "welcome.subtitle": "您平静而智能的思考、编程、学习和创作伙伴。",
    "welcome.continue": "继续",
    "chat.placeholder": "给AquaLibriaAI发消息...",
    "chat.empty.title": "今天我能帮你什么？",
    "menu.history": "聊天记录",
    "menu.coding": "编程伙伴",
    "menu.language": "语言",
    "menu.theme": "主题",
    "menu.settings": "设置",
    "menu.logout": "退出登录",
    "settings.title": "设置",
    "loading.thinking": "思考中...",
  },
  ja: {
    "welcome.greeting": "こんにちは、AquaLibriaAIです",
    "welcome.subtitle": "思考、コーディング、学習、創造のための穏やかで知的なコンパニオン。",
    "welcome.continue": "続ける",
    "chat.placeholder": "AquaLibriaAIにメッセージ...",
    "chat.empty.title": "何かお手伝いできますか？",
    "menu.history": "チャット履歴",
    "menu.coding": "コーディングパートナー",
    "menu.language": "言語",
    "menu.theme": "テーマ",
    "menu.settings": "設定",
    "menu.logout": "ログアウト",
    "settings.title": "設定",
    "loading.thinking": "考え中...",
  },
  ko: {
    "welcome.greeting": "안녕하세요, AquaLibriaAI입니다",
    "welcome.subtitle": "생각, 코딩, 학습, 창작을 위한 차분하고 지능적인 동반자입니다.",
    "welcome.continue": "계속",
    "chat.placeholder": "AquaLibriaAI에게 메시지...",
    "chat.empty.title": "무엇을 도와드릴까요?",
    "menu.history": "채팅 기록",
    "menu.coding": "코딩 파트너",
    "menu.language": "언어",
    "menu.theme": "테마",
    "menu.settings": "설정",
    "menu.logout": "로그아웃",
    "settings.title": "설정",
    "loading.thinking": "생각 중...",
  },
  ar: {
    "welcome.greeting": "مرحباً، أنا AquaLibriaAI",
    "welcome.subtitle": "رفيقك الهادئ والذكي للتفكير والبرمجة والتعلم والإبداع.",
    "welcome.continue": "متابعة",
    "chat.placeholder": "رسالة إلى AquaLibriaAI...",
    "chat.empty.title": "كيف يمكنني مساعدتك؟",
    "menu.history": "سجل المحادثات",
    "menu.coding": "شريك البرمجة",
    "menu.language": "اللغة",
    "menu.theme": "السمة",
    "menu.settings": "الإعدادات",
    "menu.logout": "تسجيل الخروج",
    "settings.title": "الإعدادات",
    "loading.thinking": "جارٍ التفكير...",
  },
  hi: {
    "welcome.greeting": "नमस्ते, मैं AquaLibriaAI हूं",
    "welcome.subtitle": "सोचने, कोडिंग, सीखने और बनाने के लिए आपका शांत, बुद्धिमान साथी।",
    "welcome.continue": "जारी रखें",
    "chat.placeholder": "AquaLibriaAI को संदेश...",
    "chat.empty.title": "मैं आज आपकी कैसे मदद कर सकता हूं?",
    "menu.history": "चैट इतिहास",
    "menu.coding": "कोडिंग पार्टनर",
    "menu.language": "भाषा",
    "menu.theme": "थीम",
    "menu.settings": "सेटिंग्स",
    "menu.logout": "लॉग आउट",
    "settings.title": "सेटिंग्स",
    "loading.thinking": "सोच रहा हूं...",
  },
  ru: {
    "welcome.greeting": "Привет, я AquaLibriaAI",
    "welcome.subtitle": "Ваш спокойный и умный компаньон для размышлений, программирования, обучения и творчества.",
    "welcome.continue": "Продолжить",
    "chat.placeholder": "Сообщение для AquaLibriaAI...",
    "chat.empty.title": "Чем я могу помочь?",
    "menu.history": "История чата",
    "menu.coding": "Партнёр по коду",
    "menu.language": "Язык",
    "menu.theme": "Тема",
    "menu.settings": "Настройки",
    "menu.logout": "Выйти",
    "settings.title": "Настройки",
    "loading.thinking": "Думаю...",
  },
  pt: {
    "welcome.greeting": "Olá, sou AquaLibriaAI",
    "welcome.subtitle": "Seu companheiro calmo e inteligente para pensar, programar, aprender e criar.",
    "welcome.continue": "Continuar",
    "chat.placeholder": "Mensagem para AquaLibriaAI...",
    "chat.empty.title": "Como posso ajudar?",
    "menu.history": "Histórico de Chat",
    "menu.coding": "Parceiro de Código",
    "menu.language": "Idioma",
    "menu.theme": "Tema",
    "menu.settings": "Configurações",
    "menu.logout": "Sair",
    "settings.title": "Configurações",
    "loading.thinking": "Pensando...",
  },
  tr: {
    "welcome.greeting": "Merhaba, ben AquaLibriaAI",
    "welcome.subtitle": "Düşünme, kodlama, öğrenme ve yaratma için sakin, zeki yoldaşınız.",
    "welcome.continue": "Devam",
    "chat.placeholder": "AquaLibriaAI'ye mesaj...",
    "chat.empty.title": "Size nasıl yardımcı olabilirim?",
    "menu.history": "Sohbet Geçmişi",
    "menu.coding": "Kodlama Ortağı",
    "menu.language": "Dil",
    "menu.theme": "Tema",
    "menu.settings": "Ayarlar",
    "menu.logout": "Çıkış",
    "settings.title": "Ayarlar",
    "loading.thinking": "Düşünüyorum...",
  },
  vi: {
    "welcome.greeting": "Xin chào, tôi là AquaLibriaAI",
    "welcome.subtitle": "Người bạn đồng hành bình tĩnh và thông minh cho suy nghĩ, lập trình, học tập và sáng tạo.",
    "welcome.continue": "Tiếp tục",
    "chat.placeholder": "Nhắn tin cho AquaLibriaAI...",
    "chat.empty.title": "Tôi có thể giúp gì?",
    "menu.history": "Lịch sử trò chuyện",
    "menu.coding": "Đối tác lập trình",
    "menu.language": "Ngôn ngữ",
    "menu.theme": "Chủ đề",
    "menu.settings": "Cài đặt",
    "menu.logout": "Đăng xuất",
    "settings.title": "Cài đặt",
    "loading.thinking": "Đang suy nghĩ...",
  },
  th: {
    "welcome.greeting": "สวัสดี ฉันคือ AquaLibriaAI",
    "welcome.subtitle": "เพื่อนคู่คิดที่สงบและชาญฉลาดของคุณ",
    "welcome.continue": "ดำเนินการต่อ",
    "chat.placeholder": "ส่งข้อความถึง AquaLibriaAI...",
    "chat.empty.title": "ฉันช่วยอะไรได้บ้าง?",
    "menu.history": "ประวัติแชท",
    "menu.coding": "พาร์ทเนอร์โค้ด",
    "menu.language": "ภาษา",
    "menu.theme": "ธีม",
    "menu.settings": "การตั้งค่า",
    "menu.logout": "ออกจากระบบ",
    "settings.title": "การตั้งค่า",
    "loading.thinking": "กำลังคิด...",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<string>(() => {
    const stored = localStorage.getItem("aqua-language");
    if (stored) return stored;
    
    const browserLang = navigator.language.split("-")[0];
    const supported = languages.find((l) => l.code === browserLang);
    return supported ? browserLang : "en";
  });

  useEffect(() => {
    localStorage.setItem("aqua-language", language);
  }, [language]);

  const setLanguage = (code: string) => {
    setLanguageState(code);
  };

  const t = (key: string): string => {
    const langTranslations = translations[language] || translations.en;
    return langTranslations[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
