import React, { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Code, Eye, Columns, Download, Save, FolderTree } from "lucide-react";
import FileExplorer, { ProjectFile } from "./FileExplorer";
import CodeViewer from "./CodeViewer";
import LivePreview from "./LivePreview";

type ViewMode = "code" | "preview" | "split";

interface AgentWorkspaceProps {
  files: ProjectFile[];
  projectId?: string;
  projectTitle?: string;
  onClose: () => void;
  onSave?: () => void;
  isSaving?: boolean;
  isStreaming?: boolean;
}

function parseFilesFromResponse(content: string): ProjectFile[] {
  const files: ProjectFile[] = [];
  const fileRegex = /---FILE:\s*(.+?)---\n([\s\S]*?)---END FILE---/g;
  let match;
  while ((match = fileRegex.exec(content)) !== null) {
    const path = match[1].trim();
    const fileContent = match[2].trim();
    files.push({ path, content: fileContent });
  }
  const partial = content.match(/---FILE:\s*(.+?)---\n([\s\S]*)$/);
  if (partial && !files.some((file) => file.path === partial[1].trim())) {
    files.push({ path: partial[1].trim(), content: partial[2].replace(/---END FILE---[\s\S]*$/, "").trimEnd() });
  }
  return files;
}

function downloadProject(files: ProjectFile[], title: string) {
  // Create a combined text file for download
  let combined = `// Project: ${title}\n// Generated by AquaLibriaAI Full-Stack Agent\n// ${files.length} files\n\n`;
  for (const file of files) {
    combined += `\n${"=".repeat(60)}\n// FILE: ${file.path}\n${"=".repeat(60)}\n\n${file.content}\n`;
  }
  const blob = new Blob([combined], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${title.replace(/\s+/g, "-").toLowerCase()}-project.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

const AgentWorkspace: React.FC<AgentWorkspaceProps> = ({ files, projectId, projectTitle = "Project", onClose, onSave, isSaving, isStreaming }) => {
  const [viewMode, setViewMode] = useState<ViewMode>("split");
  const [selectedFile, setSelectedFile] = useState<ProjectFile | null>(files[0] || null);
  const [showExplorer, setShowExplorer] = useState(true);

  useEffect(() => {
    setSelectedFile((current) => {
      if (!current) return files[0] || null;
      return files.find((file) => file.path === current.path) || files[0] || null;
    });
  }, [files]);

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: 20 }}
      className="mt-3 rounded-2xl border border-border bg-card overflow-hidden shadow-lg"
      style={{ height: "min(62dvh, 560px)" }}
    >
      {/* Toolbar */}
      <div className="flex items-center justify-between px-3 py-2 border-b border-border bg-secondary/30 shrink-0">
        <div className="flex items-center gap-2 min-w-0">
          <button onClick={() => setShowExplorer(!showExplorer)} className="p-1.5 rounded-lg hover:bg-accent transition-colors" title="Toggle explorer">
            <FolderTree className="w-3.5 h-3.5 text-foreground-muted" />
          </button>
          <span className="text-xs font-bold text-foreground truncate">{projectTitle}</span>
          <span className="text-[10px] text-foreground-muted">{files.length} files</span>
          {isStreaming && <span className="text-[10px] text-primary font-bold animate-pulse">typing</span>}
        </div>
        <div className="flex items-center gap-1">
          {/* View mode tabs */}
          <div className="flex bg-secondary rounded-xl p-0.5">
            <button onClick={() => setViewMode("code")} className={`px-2.5 py-1 rounded-lg text-[10px] font-bold transition-colors ${viewMode === "code" ? "bg-background text-foreground shadow-sm" : "text-foreground-muted hover:text-foreground"}`}>
              <Code className="w-3 h-3" />
            </button>
            <button onClick={() => setViewMode("preview")} className={`px-2.5 py-1 rounded-lg text-[10px] font-bold transition-colors ${viewMode === "preview" ? "bg-background text-foreground shadow-sm" : "text-foreground-muted hover:text-foreground"}`}>
              <Eye className="w-3 h-3" />
            </button>
            <button onClick={() => setViewMode("split")} className={`px-2.5 py-1 rounded-lg text-[10px] font-bold transition-colors ${viewMode === "split" ? "bg-background text-foreground shadow-sm" : "text-foreground-muted hover:text-foreground"}`}>
              <Columns className="w-3 h-3" />
            </button>
          </div>

          <button onClick={() => downloadProject(files, projectTitle)} className="p-1.5 rounded-lg hover:bg-accent transition-colors" title="Download">
            <Download className="w-3.5 h-3.5 text-foreground-muted" />
          </button>
          {onSave && (
            <button onClick={onSave} disabled={isSaving} className="p-1.5 rounded-lg hover:bg-accent transition-colors disabled:opacity-40" title="Save">
              <Save className={`w-3.5 h-3.5 ${isSaving ? "text-primary animate-pulse" : "text-foreground-muted"}`} />
            </button>
          )}
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-accent transition-colors">
            <X className="w-3.5 h-3.5 text-foreground-muted" />
          </button>
        </div>
      </div>

      {/* Main area */}
      <div className="flex flex-1" style={{ height: "calc(100% - 40px)" }}>
        {/* File Explorer */}
        <AnimatePresence>
          {showExplorer && (
            <motion.div
              initial={{ width: 0, opacity: 0 }}
              animate={{ width: 180, opacity: 1 }}
              exit={{ width: 0, opacity: 0 }}
              className="border-r border-border overflow-y-auto custom-scrollbar bg-secondary/20 shrink-0"
            >
              <div className="p-1.5">
                <p className="text-[10px] font-bold text-foreground-muted px-2 py-1 uppercase tracking-wider">Files</p>
                <FileExplorer files={files} selectedPath={selectedFile?.path || null} onSelectFile={setSelectedFile} />
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Content */}
        <div className="flex-1 flex min-w-0">
          {viewMode === "code" && <CodeViewer file={selectedFile} isStreaming={isStreaming} />}
          {viewMode === "preview" && <LivePreview files={files} projectId={projectId} />}
          {viewMode === "split" && (
            <>
              <div className="flex-1 flex flex-col min-w-0 border-r border-border">
                <CodeViewer file={selectedFile} isStreaming={isStreaming} />
              </div>
              <div className="flex-1 flex flex-col min-w-0">
                <LivePreview files={files} projectId={projectId} />
              </div>
            </>
          )}
        </div>
      </div>
    </motion.div>
  );
};

export { parseFilesFromResponse };
export default AgentWorkspace;
